version: '3.8'

services:
  air_hockey_rlgpu:
    build: .
    image: air_hockey_rlgpu:latest
    volumes:
      - .:/workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility]

